# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np 

#### 2. Print your NumPy version.

In [2]:
print(np.__version__)

1.21.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
a = np.random.random((2,3,5))

In [4]:
a = np.random.rand(2,3,5)

In [5]:
a = np.random.randint(1000, size=(2,3,5))

#### 4. Print *a*.


In [6]:
print(a)

[[[811 953  31 525  48]
  [925 825 102 353 714]
  [795 498 570 925 682]]

 [[319 664 129 385 434]
  [316 589 893 454 997]
  [982 850 210  18 948]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
b = np.ones(shape=(5,2,3),dtype=int)

#### 6. Print *b*.


In [8]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
a + b

# raises an error because the arrays have different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
c = b.reshape(2,3,5)
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
d = a + c
d

# it worked because now both arrays have the same shape

array([[[812, 954,  32, 526,  49],
        [926, 826, 103, 354, 715],
        [796, 499, 571, 926, 683]],

       [[320, 665, 130, 386, 435],
        [317, 590, 894, 455, 998],
        [983, 851, 211,  19, 949]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
print(a)
print(d)

# The values in the arrays differ by 1 because d = c + a and "c" is only composed of ones.

[[[811 953  31 525  48]
  [925 825 102 353 714]
  [795 498 570 925 682]]

 [[319 664 129 385 434]
  [316 589 893 454 997]
  [982 850 210  18 948]]]
[[[812 954  32 526  49]
  [926 826 103 354 715]
  [796 499 571 926 683]]

 [[320 665 130 386 435]
  [317 590 894 455 998]
  [983 851 211  19 949]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
e = a * c
e

array([[[811, 953,  31, 525,  48],
        [925, 825, 102, 353, 714],
        [795, 498, 570, 925, 682]],

       [[319, 664, 129, 385, 434],
        [316, 589, 893, 454, 997],
        [982, 850, 210,  18, 948]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
e == a

# Yes, because all the values in "c" equal to 1, so the values of "a" remain the same.

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(d_max)
print(d_min)
print(d_mean)

998
19
565.8333333333334


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
f[(d>d_min) & (d<d_mean)] = 25
f[(d>d_mean)& (d<d_max)] = 75
f[(d == d_mean)] = 50
f[(d == d_min)] = 0
f[(d == d_max)] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [19]:
print(d)
print(f)

[[[812 954  32 526  49]
  [926 826 103 354 715]
  [796 499 571 926 683]]

 [[320 665 130 386 435]
  [317 590 894 455 998]
  [983 851 211  19 949]]]
[[[ 75.  75.  25.  25.  25.]
  [ 75.  75.  25.  25.  75.]
  [ 75.  25.  75.  75.  75.]]

 [[ 25.  75.  25.  25.  25.]
  [ 25.  75.  75.  25. 100.]
  [ 75.  75.  25.   0.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [20]:
f = np.empty((2,3,5),dtype=str)

f[(d>d_min) & (d<d_mean)] = "B"
f[(d>d_mean)& (d<d_max)] = "D"
f[(d == d_mean)] = "C"
f[(d == d_min)] = "A"
f[(d == d_max)] = "E"

print(f)

[[['D' 'D' 'B' 'B' 'B']
  ['D' 'D' 'B' 'B' 'D']
  ['D' 'B' 'D' 'D' 'D']]

 [['B' 'D' 'B' 'B' 'B']
  ['B' 'D' 'D' 'B' 'E']
  ['D' 'D' 'B' 'A' 'D']]]
